repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      - id: check-case-conflict
      - id: check-merge-conflict
      - id: check-yaml
      - id: end-of-file-fixer
      - id: trailing-whitespace

  - repo: https://github.com/tox-dev/tox-ini-fmt
    rev: 1.3.0
    hooks:
      - id: tox-ini-fmt

ci:
  autoupdate_schedule: quarterly
