[tox]
requires =
    tox>=4.5
env_list =
    py{py3, 314, 313, 312, 311, 310}

[testenv]
deps =
    pytest
    pytest-cov
pass_env =
    FORCE_COLOR
commands =
    {envpython} -m pytest --cov geojson --cov tests --cov-report xml {posargs}
